### ISSUE TITLE
[Epic] PIE liquidity management

### ISSUE THREAD

**Issue by dmvt** [pie-dao/pools.piedao.org#7]
## Description

We will create a liquidity management site for PieDAO liquidity pools.

## Initiative / goal

The process of adding liquidity to a pool is painful. We don't providde an interface at all for removing liquidity. The goal of this epic is a first pass at a much less painful version of this process.

## Acceptance criteria and must have scope

- [X] Balance of individual tokens is available
- [X] Pool balance is available
- [ ] If farming rewards are available, they are displayed
- [X] There are information links (media, audits, etherscan) for each liquidity pool
- [X] Users can always see the current allocation
- [ ] There is a list of places where the pool can be bought and sold
- [ ] A user can add or remove liquidity from all assets representing the pool
- [ ] A user can add or remove liquidity via a single assets

## Stakeholders

Discord #development channel

## Visuals

![add-liquidity-single](https://piedao-productpage-improvements.netlify.app/img/page08.png)
![add-liquidity-multi](https://piedao-productpage-improvements.netlify.app/img/page09.png)
![withdraw-liquidity-single](https://piedao-productpage-improvements.netlify.app/img/page10.png)
![withdraw-liquidity-advanced](https://piedao-productpage-improvements.netlify.app/img/page11.png)
![select-a-token](https://piedao-productpage-improvements.netlify.app/img/modal.png)
